miniblog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('addpost/', views.addpost, name='addpost'),
    path('updatepost/<int:id>/', views.updatepost, name='updatepost'),
    path('deletepost/<int:id>/', views.deletepost, name='deletepost'),
    path('changepassword/', views.chngpass, name='changepassword'),
]

blog/models.py
from django.db import models

# Create your models here.
class blogPost(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField()

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm
from django.contrib.auth.models import User
from django.forms import widgets
from django.utils.translation import gettext, gettext_lazy as _
from .models import blogPost

# For signup form
class SignUpForm(UserCreationForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'first_name':'First Name', 'last_name':'Last Name', 'email':'Email'}
        widgets = {'username':forms.TextInput(attrs={'class':'form-control'}),
        'first_name':forms.TextInput(attrs={'class':'form-control'}),
        'last_name':forms.TextInput(attrs={'class':'form-control'}),
        'email':forms.EmailInput(attrs={'class':'form-control'}),
        }

# For Login form
class LoginForm(AuthenticationForm):
   username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class':'form-control'})) 
   password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class':'form-control'}))

# For Login form
class PostForm(forms.ModelForm):
    class Meta:
        model = blogPost
        fields = ['title', 'desc']
        labels = {'title':'Title', 'desc':'Description'}
        widgets = {'title':forms.TextInput(attrs={'class':'form-control'}),
                'desc':forms.Textarea(attrs={'class':'form-control'}),
                }

# For change password
class changepassform(PasswordChangeForm):
    old_password = forms.CharField(label='Old Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    new_password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    new_password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        

blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import LoginForm, SignUpForm, PostForm, changepassform
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from .models import blogPost
from django.contrib.auth.models import Group


# Create your views here.

# Home
def home(request):
    posts = blogPost.objects.all()
    return render(request, 'home.html', {'posts':posts})

# About
def about(request):
    return render(request, 'about.html')

# contact
def contact(request):
    return render(request, 'contact.html')

# Dashboard
def dashboard(request):
    if request.user.is_authenticated:
        posts = blogPost.objects.all()
        user = request.user
        full_name = user.get_full_name
        grp = user.groups.all()
        return render(request, 'dashboard.html', {'posts':posts, 'fullname':full_name, 'groups':grp})
    else:
        return HttpResponseRedirect('/login/')

# signup
def user_signup(request):
    if request.method == "POST":
        fm = SignUpForm(request.POST)
        if fm.is_valid():
            user = fm.save()
            messages.success(request, 'Congratulation!! SignUp successfully')
            group = Group.objects.get(name='author')
            user.groups.add(group)
            return render(request, 'signup.html', {'form':fm})
    else:
        fm = SignUpForm()
    return render(request, 'signup.html', {'form':fm})

# user_login
def user_login(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = LoginForm(request=request, data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                upass = form.cleaned_data['password']
                user = authenticate(username=uname, password=upass)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'Login successfully')
                    return HttpResponseRedirect('/dashboard/')
        else:
            form = LoginForm()
        return render(request, 'login.html',{'form':form})
    else:
        return HttpResponseRedirect('/dashboard/')
        

# user_logout
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

# Add Post
def addpost(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data['title']
                desc = form.cleaned_data['desc']
                Bpost = blogPost(title=title,desc=desc)
                Bpost.save()
                form = PostForm()
        else:
            form = PostForm()
        return render(request, 'addpost.html', {'form':form})
    else:
        return HttpResponseRedirect('/login/')

# Update Post
def updatepost(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pi = blogPost.objects.get(pk=id)
            form = PostForm(request.POST, instance=pi)
            if form.is_valid():
                form.save()
                messages.success(request, 'Post Updated successfully')
                return HttpResponseRedirect('/dashboard/')
        else:
            pi = blogPost.objects.get(pk=id)
            form = PostForm(instance=pi)
        return render(request, 'updatepost.html', {'form':form})
    else:
        return HttpResponseRedirect('/login/')

# Delete Post
def deletepost(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pi = blogPost.objects.get(pk=id)
            pi.delete()
            messages.success(request, 'Post Deleted successfully')
            return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')

# For Change Password with old password.
def chngpass(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            fm = changepassform(user=request.user, data=request.POST)
            if fm.is_valid():
                fm.save()
                update_session_auth_hash(request, fm.user)
                messages.success(request, 'Password Change Successfully...')
                return HttpResponseRedirect('/dashboard/')
        else:
            fm = changepassform(user=request.user)
        return render(request, 'chngpassword.html', {'form':fm})
    else:
        return HttpResponseRedirect('/login/')
   

blog/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10 my-5">
    <h3>About us...</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum aperiam excepturi laborum dolorum, qui sapiente sint nemo aspernatur ea illum eum aliquid, nesciunt libero voluptatem porro architecto repellendus ad.</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque aspernatur cumque modi expedita perferendis est aperiam distinctio repudiandae tempore. Fugit qui, quaerat vitae totam repudiandae voluptatem hic deleniti sequi dolorem!</p>
</div>
    
</div>


{% endblock content %}

blog/templates/addpost.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10 my-5">
    <h3>Add Post page...</h3>
    <form action="" method="post" novalidate>
    {% csrf_token %}

    {{form.as_p}}

    <input type="submit" value="Add" class="btn btn-success">
    <a href="{% url 'dashboard'%}" class="btn btn-danger">Cancel</a>
    </form>
    
</div>


{% endblock content %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    
<div class="container-fluid bg-dark">
{% include 'navbar.html' %}
</div>
<div class="container">
<div class="row">
<div class="col-sm-12">
{% block msg %}

{% endblock msg %}
</div>
</div>
<div class="row">

{% block side %}

{% endblock side %}

{% block content %}

{% endblock content %}



</div>
</div>
    


    <script src=" {% static 'js/jquery.js' %} "></script>
    <script src=" {% static 'js/popper.js' %} "></script>
    <script src=" {% static 'js/bootstrap.js' %} "></script>
</body>
</html>

blog/templates/chngpassword.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-4 my-5">
    <h3>Change password...</h3>
    <form action="" method="post" novalidate>
    {% csrf_token %}
    
    {% for fm in form %}
    
    {{fm.label_tag}} {{fm}} <span class="err">{{fm.errors|striptags}}</span><br>
    
    {% endfor %}
    
    <input type="submit" value="Save" class="btn btn-success">
    <a href="{% url 'dashboard'%}" class="btn btn-danger">Cancel</a>
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <p class="err">{{error}}</p>
    {% endfor %}
    {% endif %}
    </form>
    
</div>
    
</div>


{% endblock content %}

blog/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10 my-5">
    <h3>Contact us...</h3>
    <form class="row g-3">
  <div class="col-md-6">
    <label for="inputEmail4" class="form-label">Name</label>
    <input type="email" class="form-control" id="inputEmail4">
  </div>
  <div class="col-md-6">
    <label for="inputPassword4" class="form-label">Email</label>
    <input type="password" class="form-control" id="inputPassword4">
  </div>
  <div class="col-12">
    <label for="inputAddress" class="form-label">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
  </div>
  <div class="col-12">
    <label for="inputAddress2" class="form-label">Message</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
  </div>
  
  <div class="col-12">
    <button type="submit" class="btn btn-primary">Sign in</button>
  </div>
</form>

    
</div>


{% endblock content %}

blog/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block msg %}


    {% if messages %}
    {% for message in messages %}
    
    <div {% if message.tags%} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}>
    <strong>{{message}}</strong>

    <button type="button" class="btn-close" data-dismiss="alert" aria-label="close">
        <span aria-hidden="true">&times;</span>
    </button>

    

    
    
    {% endfor %}

    {% endif %}
    
  


{% endblock msg %}

{% block side %}
<div class="col-sm-2 text-white my-5 text-center">
    <h4 class="text-white my-5">Profile</h4>
    <h5>{{fullname}}</h5>
    {% for group in groups %}
    <p>{{group.name}}</p>
    {% endfor %}
    <a href="{% url 'changepassword'%}" class="text-white my-5">Change Password</a>
</div>
{% endblock side %}







{% block content %}

<div class="col-sm-10 my-5">
    <h3 class="text-white my-5">Dashboard...</h3>
    <a href="{% url 'addpost' %}" class="btn btn-success">Add Post</a>
    <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>
    {% if posts %}
    <table class="table table-hover bg-dark">
    <thead>
    <tr class="text-center">
    <th scope="col" style="width:2%">ID</th>
    <th scope="col" style="width:28%">Title</th>
    <th scope="col" style="width:55%">Description</th>
    <th scope="col" style="width:15%">Action</th>
    </tr>
    </thead>
    <tbody>
    {% for post in posts %}
    <tr>
    <td scope="row">{{post.id}}</td>
    <td>{{post.title}}</td>
    <td>{{post.desc}}</td>
    <td class="text-center">
    <a href="{% url 'updatepost' post.id %}" class="btn btn-warning btn-sm">Edit</a>
    {% if perms.blog.delete_blogpost %}
    <form action="{% url 'deletepost' post.id %}" method="post" class="d-inline">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
    
    </form>
    {% endif %}
    </td>
    </tr>
    
    {% endfor %}
    </tbody>
    </table>
    {% endif %}
</div>
{% endblock content %}

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10 my-5">
    <h3>Home page...</h3>
    {% for post in posts %}
    <div class="jumbotron jumbotron-fluid bg-dark">
  <div class="container">
    <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
    <p class="lead">{{post.desc}}</p>
  </div>
</div>
{% endfor %}
    
</div>


{% endblock content %}

blog/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10 my-5">
    <h3>Login here...</h3>
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {% for fm in form %}
    <div class="form-group">
    
    {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small> <br>
    
    </div>

    {% endfor %}
    <input type="submit" value="Login" class="btn btn-primary">

    {% if form.non_field_errors %}
    
    {% for error in form.non_field_errors %}
    
    <p class="alert alert-danger my-3">{{error}}</p>
    
    {% endfor %}
    {% endif %}


    </form>
</div>
    
</div>


{% endblock content %}

blog/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Mini Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
        
      </ul>
    </div>
  </div>
</nav>





</body>
</html>

blog/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10 my-5">
    <h3>Signup Here...</h3>
    {% if messages %}
    {% for message in messages %}
    
    <p {% if message.tags%} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
    
    {% endfor %}

    {% endif %}




    <form action="" method="post" novalidate>
    {% csrf_token %}
    {% for fm in form %}
    <div class="form-group">
    
    {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small> <br>
    
    </div>

    {% endfor %}
    <input type="submit" value="submit" class="btn btn-primary">

    {% if form.non_field_errors %}
    
    {% for error in form.non_field_errors %}
    
    <p class="alert alert-danger my-3">{{error}}</p>
    
    {% endfor %}
    {% endif %}


    </form>
    
    
</div>
    



{% endblock content %}

blog/templates/updatepost.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10 my-5">
    <h3>Update Post page...</h3>
    <form action="" method="post" novalidate>
    {% csrf_token %}

    {{form.as_p}}

    <input type="submit" value="Update" class="btn btn-success">
    <a href="{% url 'dashboard'%}" class="btn btn-danger">Cancel</a>
    </form>
    
</div>


{% endblock content %}